# Generated by Django 4.2.6 on 2024-03-05 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam_schedule', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examschedule',
            name='mode',
        ),
    ]
